### ISSUE TITLE
Missing: Preview form - in a new tab.

### ISSUE THREAD

**Issue by paaljoachim** [formello-forms/formello#5]
I save the form as a draft and click to Preview.
I see this:
![Screenshot 2023-04-28 at 13 05 09](https://user-images.githubusercontent.com/5323259/235131859-aec38e2a-8767-4508-9707-b73934a73a72.jpg)

I expect to see the standard Preview drop down in in post or page:
![Screenshot 2023-04-28 at 13 05 23](https://user-images.githubusercontent.com/5323259/235131935-5efa3ac3-113c-4ae9-9d07-fabded98e341.jpg)

As I would like to preview the form on the frontend in a new tab.

**Comment by Tropicalista** [comment]
This is not possible, because forms are custom post type private and are meant to be used only embedded in a page or post.
