### ISSUE TITLE
The publisher encountered an unexpected error

### ISSUE THREAD

**Issue by dvinz** [formello-forms/formello#8]
Hello,

error = "The publisher encountered an unexpected error"

Wordpress 6.3
PHP | 7.4.33

Error when clic to "display rules" "Conditions"

Tabs@https://exemple.com/wp-content/plugins/popper/build/index.js?ver=fa9a03425282a014f736:2220:7
St@https://exemple.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:47627
$s@https://exemple.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:120574
Sl@https://exemple.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:88651
kl@https://exemple.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:88579
bl@https://exemple.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:88440
sl@https://exemple.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:85264
dl@https://exemple.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:85651
Nn@https://exemple.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:32464
n/ol/<@https://exemple.com/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:1:83216

Best regards

**Comment by Tropicalista** [comment]
Hi, I have noticed this error. 

It's due to some change on latest WP update. I will fix asap.

Thanks for reporting.

**Comment by Tropicalista** [comment]
Can you try to update https://it.wordpress.org/plugins/popper/ to latest and let me know if the issue is solved?
